/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

/**
 *
 * @author laboratorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jSair = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jCadastroPessoa = new javax.swing.JMenuItem();
        jEditarExcluirPessoa = new javax.swing.JMenuItem();
        jCadastroVeiculo = new javax.swing.JMenuItem();
        jEditarExcluirVeiculo = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jRelatorioPessoa = new javax.swing.JMenuItem();
        jRelatorioVeiculo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jmArquivo.setText("Arquivo");

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jSair);

        jMenuBar1.add(jmArquivo);

        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jCadastroPessoa.setText("Cadastro de Aluno");
        jCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroPessoaActionPerformed(evt);
            }
        });
        jmCadastro.add(jCadastroPessoa);

        jEditarExcluirPessoa.setText("Editar e excluir Pessoa");
        jEditarExcluirPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarExcluirPessoaActionPerformed(evt);
            }
        });
        jmCadastro.add(jEditarExcluirPessoa);

        jCadastroVeiculo.setText("Cadastro de Veiculo");
        jCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroVeiculoActionPerformed(evt);
            }
        });
        jmCadastro.add(jCadastroVeiculo);

        jEditarExcluirVeiculo.setText("Editar e excluir Veiculo");
        jEditarExcluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarExcluirVeiculoActionPerformed(evt);
            }
        });
        jmCadastro.add(jEditarExcluirVeiculo);

        jMenuBar1.add(jmCadastro);

        jmRelatorio.setText("Relatório");

        jRelatorioPessoa.setText("Relatório de Pessoa");
        jRelatorioPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioPessoaActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatorioPessoa);

        jRelatorioVeiculo.setText("Relatório de Veiculo");
        jRelatorioVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioVeiculoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatorioVeiculo);

        jMenuBar1.add(jmRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroPessoaActionPerformed
        CadastrarPessoa cadastro = new CadastrarPessoa();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jCadastroPessoaActionPerformed

    private void jEditarExcluirPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarExcluirPessoaActionPerformed
        EditarPessoa editarExcluir = new EditarPessoa();
        editarExcluir.setVisible(true);
    }//GEN-LAST:event_jEditarExcluirPessoaActionPerformed

    private void jRelatorioPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioPessoaActionPerformed
        RelatorioPessoas relatorio = new RelatorioPessoas();
        relatorio.setVisible(true);
    }//GEN-LAST:event_jRelatorioPessoaActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    private void jCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroVeiculoActionPerformed
        CadastrarVeiculo cadastro = new CadastrarVeiculo();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jCadastroVeiculoActionPerformed

    private void jEditarExcluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarExcluirVeiculoActionPerformed
        EditarVeiculo editarExcluir = new EditarVeiculo();
        editarExcluir.setVisible(true);
    }//GEN-LAST:event_jEditarExcluirVeiculoActionPerformed

    private void jRelatorioVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioVeiculoActionPerformed
        RelatorioVeiculos relatorio = new RelatorioVeiculos();
        relatorio.setVisible(true);

    }//GEN-LAST:event_jRelatorioVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadastroPessoa;
    private javax.swing.JMenuItem jCadastroVeiculo;
    private javax.swing.JMenuItem jEditarExcluirPessoa;
    private javax.swing.JMenuItem jEditarExcluirVeiculo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jRelatorioPessoa;
    private javax.swing.JMenuItem jRelatorioVeiculo;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmRelatorio;
    // End of variables declaration//GEN-END:variables
}
